---
-
  name: "Templating /etc/exports"
  template: src=exports.j2 dest=/etc/exports owner=root group=root mode=644
  delegate_to: "{{ nfs_server }}"
  run_once: true
  sudo: true
#-
#  name : Restart the NFS Server
#  service: name=nfs state=restarted
#  delegate_to: "{{ nfs_server }}"
#  run_once: true
#  sudo: true
