---
- name: "Install open ldap package yum"
  action: yum pkg={{ item }} state=installed 
  with_items:
    - openldap
    - openldap-clients
    - sssd
    - sssd-common
    - sssd-client
    - nss
    - nss-tools
  sudo: true
  when: ansible_os_family == 'RedHat'

- name: "Install open ldap package apt"
  action: apt pkg={{ item }} state=installed 
  with_items:
    - ldap-utils
    - sssd 
    - libpam-sss 
  sudo: true
  when: ansible_os_family == 'Debian'
