---
ldapDomain: "monash.edu.au" 
ldapUri: "ldaps://ldapserver.com/"
ldapDn: "cn=ldapbind,cn=users,dc=monash,dc=edu,dc=au" 
ldapPassword: "secret"
ldapBase: "cn=users,dc=monash,dc=edu,dc=au"
ldapUserClass: "user"
ldapUserHomeDirectory: "unixHomeDirectory"
ldapUserPricipal: "userPrincipalName"
ldapGroupBase: "ou=groups,dc=monash,dc=edu,dc=au"
tlsCaCertDirectory: "/etc/openldap/certs"
tlsCaCertFile: "/etc/openldap/certs/ca.pem"
ldapCaCertFileSource: "/etc/openldap/certs"
cacertFile: "ca.pem"
ldapRfc2307: ""
ldapRfc2307Pam: ""

