rpm_package: "http://dev.mysql.com/get/mysql-community-release-el7-5.noarch.rpm"

server_packages:
  - python
  - python-devel
  - MySQL-python
  - mysql-community-server

client_packages:
  - mysql-community-client
  - python
  - MySQL-python
